# 获取符文标签
# {0} 是变量符，如&b[&c♥&b]
tag: '&b[{0}&b]'
# 空槽位变量表示符，如&b[&7◇&b]
emptySlot: '&7◇'

xiangqian:
  title: '&a符文镶嵌'
  item: '&a点击镶嵌'
  lore:
  - '&7点击此处即可镶嵌'
  - '&7一格子防装备，二格子放材料。'
zhaichu:
  title: '&c符文摘除'
  item: '&7须知'
  lore:
  - '&c&m-=-=-=-=-=-=-=-=-=-=-=-=-'
  - '&7从先到后'
  - '&7最多显示45个镶嵌材料'
  - '&7每行最多显示9个镶嵌材料'
  - '&7最多显示5行材料'
  - '&7多余的会在留够空间后'
  - '&7重新打开时添加'
  - '&7GUI行相对对应镶嵌行'
  - '&7GUI列相对对应镶嵌行对应镶嵌物品'
  - '&c&m-=-=-=-=-=-=-=-=-=-=-=-=-'

message:
  emptyRune: '&c请您放入符文!'
  emptyItem: '&c请您放入装备!'
  noRune: '&c请确定您放入的材料是符文吗？'
  noItem: '&c该装备没有镶嵌孔不能镶嵌!'
  moreItem: '&c请拿走过多的装备物品!'
  successXQ: '&a镶嵌 {0} 成功！战斗力嗖的一下上升了~'
  noHand: '&a请将要拆解的物品拿在手上！'
  moreHand: '&a请不要一次拿多个在手上！'
  successZC: '&a摘除 {0} 成功！~'
  givePlayer: '&a{0} 向您发送了 &c[{1}&c]&b*&7{2}'
  giveMe: '&a你获得了 &c[{0}&c]&b*&7{1}'